### ISSUE TITLE
critical-selector inefficient with @media rules

### ISSUE THREAD

**Issue by jkphl** [zgreen/postcss-critical-css#12] opened 2017-05-11 15:14 UTC
When using `critical-selector` inside a `@media` rule, the complete rule content will be seen as critical. Based on your `example.css`:

```css
@media {
	.foo {
		critical-selector: this;
		display: flex;
		width: calc(100% - 200px);
	}

	.bar {
		border: 10px solid gold;
		height: 100%;
	}

	.baz::before {
		content: 'test';
		position: fixed;
	}
}
```

I'd expect only the `.foo` selector to be considered critical, resulting in

```css
@media{.foo{display:flex;width:calc(100% - 200px)}}
```

However, the whole stylesheet is copied to `critical.css`.

**Comment by zgreen** [comment] 2017-05-11 17:53
Hmm, yeah. While working on https://github.com/zgreen/postcss-critical-css/issues/11 I think I may have found the cause of this; I'll try and roll a fix for this into that work. Thanks for the report.

**Comment by jkphl** [comment] 2017-05-12 08:52
I wish I could help you with fixing this but unfortunately I won't be available for the next 2 weeks. We're about launching a project where we'd need this, so the sooner there's a fix the better. Thank you! :)

**Comment by zgreen** [comment] 2017-05-15 11:59
@jkphl I've got a bit more work to do on it (mostly clean up) but #13 should address this issue (the test passes, currently). I'm going to try and merge it in the next day or two.

**Comment by jkphl** [comment] 2017-05-16 08:19
Sounds great, @zgreen, thanks! Very much looking forward to the next release!

**Comment by zgreen** [comment] 2017-05-19 12:43
Resolved by https://github.com/zgreen/postcss-critical-css/pull/13

**Closed by zgreen** 2017-05-19 12:43 UTC
Labels: in development
